$(".slider").slick({
  dots: !1,
  fade: !0,
  infinite: !0,
  autoplay: !0,
  arrows: !0,
  speed: 600,
  prevArrow: '<i class="icofont-arrow-right dandik"></i>',
  nextArrow: '<i class="icofont-arrow-left bamdik"></i>',
  slidesToShow: 1,
  slidesToScroll: 1,
  responsive: [
    { breakpoint: 1200, settings: { slidesToShow: 1, slidesToScroll: 1 } },
    { breakpoint: 992, settings: { slidesToShow: 1, slidesToScroll: 1 } },
    { breakpoint: 768, settings: { slidesToShow: 1, slidesToScroll: 1 } },
    {
      breakpoint: 576,
      settings: { slidesToShow: 1, slidesToScroll: 1, arrows: !1 },
    },
  ],
}),
  $(".sug_slick_slider").slick({
    dots: !1,
    infinite: !0,
    autoplay: !0,
    arrows: !0,
    speed: 1e3,
    prevArrow: '<i class="icofont-arrow-right dandik"></i>',
    nextArrow: '<i class="icofont-arrow-left bamdik"></i>',
    slidesToShow: 5,
    slidesToScroll: 2,
    responsive: [
      { breakpoint: 1200, settings: { slidesToShow: 4, slidesToScroll: 4 } },
      { breakpoint: 992, settings: { slidesToShow: 3, slidesToScroll: 3 } },
      { breakpoint: 768, settings: { slidesToShow: 2, slidesToScroll: 2 } },
      {
        breakpoint: 576,
        settings: { slidesToShow: 2, slidesToScroll: 2, arrows: !1 },
      },
    ],
  }),
  $(".new-collection-slider").slick({
    dots: !1,
    infinite: !0,
    autoplay: !0,
    arrows: !0,
    speed: 800,
    prevArrow: '<i class="icofont-arrow-right dandik"></i>',
    nextArrow: '<i class="icofont-arrow-left bamdik"></i>',
    slidesToShow: 5,
    slidesToScroll: 1,
    responsive: [
      { breakpoint: 1200, settings: { slidesToShow: 4, slidesToScroll: 2 } },
      { breakpoint: 992, settings: { slidesToShow: 3, slidesToScroll: 3 } },
      { breakpoint: 768, settings: { slidesToShow: 2, slidesToScroll: 2 } },
      {
        breakpoint: 576,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          variableWidth: !0,
          arrows: !1,
        },
      },
    ],
  }),
  $(".brand-slider").slick({
    dots: !1,
    infinite: !0,
    autoplay: true,
    arrows: !0,
    speed: 800,
    prevArrow: '<i class="icofont-arrow-right dandik"></i>',
    nextArrow: '<i class="icofont-arrow-left bamdik"></i>',
    slidesToShow: 5,
    slidesToScroll: 1,
    responsive: [
      { breakpoint: 1200, settings: { slidesToShow: 4, slidesToScroll: 4 } },
      { breakpoint: 992, settings: { slidesToShow: 3, slidesToScroll: 3 } },
      { breakpoint: 768, settings: { slidesToShow: 2, slidesToScroll: 2 } },
      {
        breakpoint: 576,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 1,
          variableWidth: !0,
          arrows: !1,
        },
      },
    ],
  }),
  $(".testimonial-slider").slick({
    dots: !1,
    infinite: !0,
    autoplay: !0,
    arrows: !0,
    fade: !1,
    speed: 1e3,
    centerMode: !0,
    centerPadding: "250px",
    slidesToShow: 1,
    slidesToScroll: 1,
    prevArrow: '<i class="icofont-arrow-right dandik"></i>',
    nextArrow: '<i class="icofont-arrow-left bamdik"></i>',
    responsive: [
      {
        breakpoint: 1200,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          centerPadding: "250px",
        },
      },
      {
        breakpoint: 992,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
          centerPadding: "130px",
        },
      },
      {
        breakpoint: 768,
        settings: { slidesToShow: 1, slidesToScroll: 1, centerPadding: "40px" },
      },
      {
        breakpoint: 576,
        settings: {
          arrows: !1,
          slidesToShow: 1,
          slidesToScroll: 1,
          centerPadding: "10px",
        },
      },
    ],
  }),
  $(".blog-slider").slick({
    dots: !1,
    infinite: !0,
    autoplay: !1,
    arrows: !0,
    speed: 800,
    prevArrow: '<i class="icofont-arrow-right dandik"></i>',
    nextArrow: '<i class="icofont-arrow-left bamdik"></i>',
    slidesToShow: 3,
    slidesToScroll: 1,
    responsive: [
      { breakpoint: 1200, settings: { slidesToShow: 3, slidesToScroll: 3 } },
      { breakpoint: 992, settings: { slidesToShow: 2, slidesToScroll: 2 } },
      { breakpoint: 768, settings: { slidesToShow: 1, slidesToScroll: 1 } },
      {
        breakpoint: 576,
        settings: { slidesToShow: 1, slidesToScroll: 1, arrows: !1 },
      },
    ],
  });
